---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}-http"
  labels:
    app: "{{ .Chart.Name }}"
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: "{{ .Chart.Name }}-http"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Chart.Name }}-http"
  labels:
    app: "{{ .Chart.Name }}"
spec:
  replicas: {{ .Values.content.replicas }}
  selector:
    matchLabels:
      app: "{{ .Chart.Name }}-http"
  template:
    metadata:
      labels:
        app: "{{ .Chart.Name }}-http"
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: "{{ .Chart.Name }}-pvc"
      containers:
        - image: spaship/httpd
          name: spaship
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: data
              mountPath: "/var/www/html"
