apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.deployment.name }}-copy-content
  annotations:
    # TODO: Change to helm hook
    argocd.argoproj.io/hook: Sync
#    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: "{{ .Values.deployment.name }}-pvc"
      containers:
        - name: sync
          image: "{{ .Values.content.image.repository }}:{{ .Values.content.image.tag }}"
          imagePullPolicy: {{ .Values.content.image.pullPolicy }}
          command: ["rsync", "-rDvh"]
          args: ["/content/", "/target/"]
          volumeMounts:
            - name: data
              mountPath: "/target/"
      restartPolicy: Never
  backoffLimit: 0
