apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Values.content.pvc.name }}"
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
