---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}-restapi"
  labels:
    app: "{{ .Chart.Name }}"
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: "{{ .Chart.Name }}-restapi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Chart.Name }}-restapi"
  labels:
    app: "{{ .Chart.Name }}"
spec:
  replicas: {{ .Values.restapi.replicas }}
  selector:
    matchLabels:
      app: "{{ .Chart.Name }}-restapi"
  template:
    metadata:
      labels:
        app: "{{ .Chart.Name }}-restapi"
    spec:
      containers:
        - name: restapi
          image: "{{ .Values.restapi.image.repository }}:{{ .Values.restapi.image.tag }}"
          imagePullPolicy: {{ .Values.restapi.image.pullPolicy }}
          ports:
            - containerPort: 8080
