apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.deployment.name }}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: local-storage