apiVersion: batch/v1
kind: Job
metadata:
  name: copy-content
  annotations:
    argocd.argoproj.io/hook: Sync
#    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: http-backend-data
      containers:
        - name: sync
          image: lkrzyzanek/test-content-image:catalog
          imagePullPolicy: Always
          command: ["rsync", "-avh"]
          args: ["/content/", "/target/"]
          volumeMounts:
            - name: data
              mountPath: "/target/"
        - name: sync-spa
          image: lkrzyzanek/test-content-image:home-spa
          imagePullPolicy: Always
          command: ["rsync", "-avh"]
          args: ["/content/", "/target/home-spa"]
          volumeMounts:
            - name: data
              mountPath: "/target/"
      restartPolicy: Never
  backoffLimit: 0