apiVersion: batch/v1
kind: Job
metadata:
  name: copy-content
  annotations:
    argocd.argoproj.io/hook: Sync
#    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: spaship-data
      containers:
        - name: sync
          image: lkrzyzanek/helloworld-image-content:1.0
          command: ["rsync", "-avh"]
          args: ["/content/", "/target/"]
          volumeMounts:
            - name: data
              mountPath: "/target/"
        - name: sync-spa1
          image: lkrzyzanek/helloworld-image-content:2.0
          command: ["rsync", "-avh"]
          args: ["/content/", "/target/spa1/"]
          volumeMounts:
            - name: data
              mountPath: "/target/"
      restartPolicy: Never
  backoffLimit: 0