
# Content Values
content:
  replicas: 1
  image:
    repository: lkrzyzanek/helloworld-image-content
    tag: "3.0"
    pullPolicy: Always

# REST API Values
restapi:
  replicas: 1
  image:
    repository: lkrzyzanek/helloworld-restapi
    tag: "1.0"
    pullPolicy: IfNotPresent