
ingress:
  host: "minikube.info"

# Content Values
content:
  replicas: 1
  image:
    repository: lkrzyzanek/helloworld-image-content
    tag: "2.0"
    pullPolicy: IfNotPresent
  pvc:
    name: http-backend-data

# REST API Values
restapi:
  replicas: 1
  image:
    repository: lkrzyzanek/helloworld-restapi
    tag: "1.0"
    pullPolicy: IfNotPresent