deployment:
  name: "content-restapi-ingress"

ingress:
  host: "minikube.info"

# Content Values
content:
  replicas: 1
  image:
    repository: lkrzyzanek/helloworld-image-content
    tag: "2.0"
    pullPolicy: IfNotPresent

# REST API Values
restapi:
  replicas: 1
  image:
    repository: lkrzyzanek/helloworld-restapi
    tag: "1.0"
    pullPolicy: IfNotPresent