---
apiVersion: v1
kind: Service
metadata:
  name: spaship
  labels:
    app: spaship
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 80
  selector:
    app: spaship
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spaship
  labels:
    app: spaship
spec:
  selector:
    matchLabels:
      app: spaship
  template:
    metadata:
      labels:
        app: spaship
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: spaship-data
      containers:
        - image: spaship/httpd
          name: spaship
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: data
              mountPath: "/var/www/html"
